export const environment = {
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '',
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
}

// NEXT_PUBLIC_SUPABASE_URL=https://pxyxubjcqczgwjfhjaqz.supabase.co
// NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_D70VY-ZFI-Zwz-hzj_yQyg_F3Wc-HJE
// SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4eXh1YmpjcWN6Z3dqZmhqYXF6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjAxNzM5MywiZXhwIjoyMTAxNTkzMzkzfQ.nlf9aHRhzFu5pOT-D3ylwF-__-dXFhbKL1DEJcYcaQY